# Default values for fluentd-cloudwatch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nehayward/fluentd-cloudwatch
  tag: latest
  pullPolicy: IfNotPresent

aws: 
  access_key: 
  secret_key: 
  region: us-west-2
  loggroup: 

